### Importing NumPy

In [2]:
import numpy as np

### Creating Arrays in NumPy

In [3]:
arr_1d=np.array([1,2,3,4,5])
print(f"1D array is:\n{arr_1d}\n")
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"2D array is:\n{arr_2d}")

1D array is:
[1 2 3 4 5]

2D array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### List vs NumPy array

In [5]:
py_list=[1,2,3]
print(f"Python List multiplication: {py_list*2}\n")

np_array=np.array([1,2,3])
print(f"NumPy Array multiplication: {np_array*2}\n")

Python List multiplication: [1, 2, 3, 1, 2, 3]

NumPy Array multiplication: [2 4 6]



### Compairing List and NumPy array 

In [7]:
import time # Not good practice to import here, but this is learning phase

start=time.time()
py_list=[num*2 for num in range(1000000)]
print(f"Time taken to do operation with Python List: {time.time()-start}\n")

start = time.time()
np_array=np.arange(1000000)
print(f"Time taken to do operation with NumPy array: {time.time()-start}")

Time taken to do operation with Python List: 0.0397486686706543

Time taken to do operation with NumPy array: 0.001956939697265625


### Creating array from scratch

In [10]:
zero_array=np.zeros((2,2))
print(f"Zero array:\n{zero_array}\n")

ones_array=np.ones((2,2))
print(f"Ones array:\n{ones_array}\n")

full_array=np.full((2,2),5) # Constant matrice
print(f"Full array:\n{full_array}\n")

random_array=np.random.random((2,2))
print(f"Random array:\n{random_array}\n")

sequence_array=np.arange(0,10,2)
print(f"Sequence array:\n{sequence_array}\n")

Zero array:
[[0. 0.]
 [0. 0.]]

Ones array:
[[1. 1.]
 [1. 1.]]

Full array:
[[5 5]
 [5 5]]

Random array:
[[0.43404713 0.0779594 ]
 [0.64967379 0.94285185]]

Sequence array:
[0 2 4 6 8]



### Vector, Matrix and Tensor

In [3]:
vector=np.array([1,2,3])
print(f"Vector:\n{vector}\n")

matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]
                 ])
print(f"Matrix:\n{matrix}\n")

tensor=np.array([[[1,2], [3,4]], 
                 [[5,6], [7,8]]
                 ])
print(f"Tensor:\n{tensor}")

Vector:
[1 2 3]

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Tensor:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [ ]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]
              ])
print(f"Shape: {arr.shape}")
print(f"Dimension: {arr.ndim}")
print(f"Size: {arr.size}")
print(f"DType: {arr.dtype}")

Shape: (3, 3)
Dimension: 2
Size: 9
DType: <U21


### Array Reshaping

In [ ]:
arr=np.arange(12)
print(f"Original array:\n{arr}\n")

reshape=arr.reshape((3,4))
print(f"Reshaped array:\n{reshape}\n")

flattend=reshape.flatten()
print(f"Flattend array:\n{flattend}\n")

# Returns view instead of copy
raveled=reshape.ravel()
print(f"Raveled array:\n{raveled}\n")

# Transpose
transpose=reshape.T
print(f"Transposed array:\n{transpose}\n")

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattend array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
