### Importing NumPy

In [1]:
import numpy as np

### Creating Arrays in NumPy

In [6]:
arr_1d=np.array([1,2,3,4,5])
print(f"1D array is:\n{arr_1d}\n")
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"2D array is:\n{arr_2d}")

1D array is:
[1 2 3 4 5]

2D array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### List vs NumPy array